version: '3.8'

services:
  jupyterhub:
    build: .
    image: my_jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub/data
    ports:
      - "10201:8000"
    networks:
      - jupyterhub
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 4_group
      POSTGRES_PASSWORD: 4_group
      POSTGRES_DB: 4DB
    volumes:
      - ./dataBase/init_scripts/init.sql:/docker-entrypoint/initdb.d/init.sql
    ports:
      - "10202:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "4_group", "-W", "4_group"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  jupyterhub_data:

networks:
  jupyterhub:
    name: jupyterhub